# scReportEnrichment: Input Normalization --------------------------------------
#
# Dispatcher that recognizes input type (data.frame, clusterProfiler enrichResult,
# or named list of data.frames) and routes to the appropriate normalizer.
#
# Output is always a single data.frame conforming to the internal ORA schema.


#' Validate column_map structure
#'
#' Restricts mappable fields to ORA_MAPPABLE_COLS. Checks names, values,
#' and prevents mapping of internal/derived columns like result_id.
#'
#' @param column_map Named character vector.
#' @param df Input data.frame (for column existence check).
#' @return Invisible TRUE, or stops with error.
#' @keywords internal
validate_column_map <- function(column_map, df) {
  if (is.null(column_map)) return(invisible(TRUE))

  if (!is.character(column_map) || is.null(names(column_map))) {
    stop("column_map must be a named character vector, e.g. c(term_id = 'pathway_id', p_adjust = 'padj')")
  }

  if (any(names(column_map) == "")) {
    stop("All names in column_map must be non-empty. Use c(internal_field = 'your_column').")
  }

  # Reject internal/derived fields
  blocked <- setdiff(names(column_map), ORA_MAPPABLE_COLS)
  if (length(blocked) > 0L) {
    if ("result_id" %in% blocked) {
      stop(
        "Column 'result_id' cannot be mapped via column_map. ",
        "result_id is an internal primary key generated by scReportEnrichment. ",
        "If your input contains a source identifier, use a different column name."
      )
    }
    stop(
      "column_map target(s) not allowed: ", paste(blocked, collapse = ", "), "\n",
      "Mappable fields: ", paste(ORA_MAPPABLE_COLS, collapse = ", "), "\n",
      "Internal/derived columns (result_id, gene_ratio_num, background_ratio_num, genes) ",
      "are generated automatically."
    )
  }

  # Names must not be duplicated
  if (anyDuplicated(names(column_map))) {
    stop("Duplicate target field names in column_map: ",
         paste(names(column_map)[duplicated(names(column_map))], collapse = ", "))
  }

  # All values must exist in the input data.frame
  missing_cols <- setdiff(column_map, names(df))
  if (length(missing_cols) > 0L) {
    stop(
      "column_map references non-existent column(s): ", paste(missing_cols, collapse = ", "), "\n",
      "Available columns: ", paste(names(df), collapse = ", ")
    )
  }

  invisible(TRUE)
}


#' Normalize enrichment input to the internal ORA schema
#'
#' Accepts a data.frame, a clusterProfiler enrichResult, or a named list
#' of data.frames/enrichResults. Routes to the appropriate normalizer and
#' returns a single standardised data.frame.
#'
#' @param enrichment One of:
#'   \itemize{
#'     \item A data.frame with enrichment results.
#'     \item A clusterProfiler \code{enrichResult} object.
#'     \item A named list of data.frames or enrichResult objects.
#'   }
#' @param column_map Optional named character vector mapping input column
#'   names to internal schema column names. Only used for generic data.frames.
#' @param comparison Character label for single-table inputs.
#' @return A data.frame conforming to the internal ORA schema.
#' @keywords internal
normalize_input <- function(enrichment, column_map = NULL, comparison = NULL) {
  # ---- GSEA rejection (must come before enrichResult check) ----
  if (inherits(enrichment, "gseaResult")) {
    stop(
      "GSEA result objects are not supported in v0.1.0. ",
      "Please use an ORA enrichResult or wait for the GSEA schema."
    )
  }

  # Detect clusterProfiler enrichResult (S4 object)
  if (inherits(enrichment, "enrichResult")) {
    return(normalize_clusterprofiler(enrichment, comparison = comparison))
  }

  # Named list: iterate and combine
  if (is.list(enrichment) && !is.data.frame(enrichment)) {
    return(normalize_list(enrichment, column_map = column_map))
  }

  # Generic data.frame
  if (is.data.frame(enrichment)) {
    return(normalize_dataframe(enrichment, column_map = column_map,
                               comparison = comparison))
  }

  stop(
    "enrichment must be a data.frame, a clusterProfiler enrichResult, ",
    "or a named list of data.frames/enrichResults."
  )
}


# ---- data.frame normalizer ---------------------------------------------------

#' Normalize a generic data.frame to internal schema
#'
#' @param df A data.frame of enrichment results.
#' @param column_map Named character vector for column mapping.
#' @param comparison Optional comparison label.
#' @return Standardised data.frame.
#' @keywords internal
normalize_dataframe <- function(df, column_map = NULL, comparison = NULL) {
  validate_column_map(column_map, df)

  if (nrow(df) == 0L) {
    out <- empty_ora_table()
    return(out)
  }

  out <- data.frame(stringsAsFactors = FALSE)

  # Apply explicit column_map if provided
  if (!is.null(column_map) && length(column_map) > 0) {
    for (target in names(column_map)) {
      src <- column_map[[target]]
      out[[target]] <- as.character(df[[src]])
    }
  }

  # Auto-detect remaining columns (will error on ambiguity)
  out <- auto_detect_columns(df, out, column_map_used = names(column_map))

  # Fill defaults (always generates internal result_ids)
  out <- fill_normalized_defaults(out, df, comparison)

  # Ensure all internal columns present and ordered
  for (col in ORA_ALL_COLS) {
    if (!col %in% names(out)) {
      out[[col]] <- rep(if (col == "genes") list(character(0)) else NA_character_,
                        nrow(out))
    }
  }

  # Handle list-column for genes
  if (!is.list(out[["genes"]])) {
    out[["genes"]] <- lapply(as.character(out[["genes"]]), parse_gene_string)
  }

  out <- out[, ORA_ALL_COLS, drop = FALSE]

  # Type coercion
  out[["p_value"]] <- as.numeric(out[["p_value"]])
  out[["p_adjust"]] <- as.numeric(out[["p_adjust"]])
  out[["q_value"]] <- as.numeric(out[["q_value"]])
  out[["gene_count"]] <- as.integer(out[["gene_count"]])
  out[["gene_ratio_num"]] <- as.numeric(out[["gene_ratio_num"]])
  out[["background_ratio_num"]] <- as.numeric(out[["background_ratio_num"]])

  # Warn if user input had a result_id column (it's being ignored)
  if ("result_id" %in% names(df) && !"result_id" %in% names(column_map %||% character(0))) {
    warning(
      "Input data.frame contains a 'result_id' column, which will be ignored. ",
      "scReportEnrichment generates its own globally-unique result_id values. ",
      "Rename your source ID column if you need to preserve it."
    )
  }

  out
}


#' Auto-detect columns from a generic data.frame
#'
#' Deterministic column matching. If multiple candidates exist for the same
#' target, the function STOPs with a descriptive error telling the user to
#' use \code{column_map}.
#'
#' @param df Input data.frame.
#' @param out Partially-built output data.frame.
#' @param column_map_used Character vector of target fields already set via
#'   column_map (these are skipped during auto-detection).
#' @return Updated output data.frame with auto-detected columns.
#' @keywords internal
auto_detect_columns <- function(df, out, column_map_used = character(0)) {
  candidates <- list(
    term_id    = c("term_id", "ID", "pathway_id", "go_id", "kegg_id"),
    term_name  = c("term_name", "Description", "term", "pathway", "pathway_name"),
    database   = c("database", "source", "category"),
    p_value    = c("p_value", "pvalue", "p.val", "Pvalue"),
    p_adjust   = c("p_adjust", "p.adjust", "padj", "adj.P.Val", "FDR"),
    q_value    = c("qvalue", "q_value", "q.val"),
    gene_ratio = c("gene_ratio", "GeneRatio", "ratio"),
    background_ratio = c("background_ratio", "BgRatio", "bg_ratio"),
    gene_count = c("gene_count", "Count", "n_genes", "gene_count_int"),
    gene_ids_raw = c("gene_ids_raw", "geneID", "gene_list", "gene_symbols"),
    input_direction = c("input_direction", "direction", "regulation",
                        "up_down", "change"),
    comparison = c("comparison", "cluster", "celltype", "condition",
                   "contrast", "group")
  )

  for (target in names(candidates)) {
    if (target %in% names(out)) next       # already set via column_map
    if (target %in% column_map_used) next  # explicitly mapped

    cands <- candidates[[target]]
    hits <- intersect(cands, names(df))

    if (length(hits) == 0L) next

    if (length(hits) > 1L) {
      stop(
        "Ambiguous columns for internal field '", target, "': ",
        paste(hits, collapse = ", "), ".\n",
        "Use column_map = c(", target, ' = "', hits[1],
        '") to select one explicitly.'
      )
    }

    if (target != "genes") {
      out[[target]] <- as.character(df[[hits[1]]])
    }
  }

  # gene_ids_raw: only auto-detect if not already set
  if (!"gene_ids_raw" %in% names(out)) {
    gene_raw_cands <- candidates[["gene_ids_raw"]]
    gene_hits <- intersect(gene_raw_cands, names(df))
    gene_hits <- setdiff(gene_hits, column_map_used)
    if (length(gene_hits) == 1L) {
      out[["gene_ids_raw"]] <- as.character(df[[gene_hits[1]]])
    }
  }

  out
}


#' Fill default values for a normalized data.frame
#'
#' result_id is ALWAYS generated by the package (never from user input).
#'
#' @param out Current output data.frame.
#' @param df Original input data.frame.
#' @param comparison Comparison label.
#' @return Completed data.frame.
#' @keywords internal
fill_normalized_defaults <- function(out, df, comparison) {
  n <- max(nrow(out), nrow(df))
  comp <- comparison %||% "enrichment"

  # ALWAYS generate internal result_ids (never from user input)
  if (!"result_id" %in% names(out) || all(is.na(out[["result_id"]]))) {
    out[["result_id"]] <- make_scoped_result_ids(n, comp)
  }

  if (!"comparison" %in% names(out)) {
    out[["comparison"]] <- rep(comp, n)
  }

  if (!"database" %in% names(out)) {
    out[["database"]] <- rep("custom", n)
  }

  # Parse ratios
  if ("gene_ratio" %in% names(out)) {
    if (!"gene_ratio_num" %in% names(out)) {
      out[["gene_ratio_num"]] <- vapply(as.character(out[["gene_ratio"]]),
                                        ratio_to_numeric, numeric(1))
    }
  }

  if ("background_ratio" %in% names(out)) {
    if (!"background_ratio_num" %in% names(out)) {
      out[["background_ratio_num"]] <- vapply(
        as.character(out[["background_ratio"]]),
        ratio_to_numeric, numeric(1))
    }
  }

  # Parse gene strings
  if ("gene_ids_raw" %in% names(out) && !"genes" %in% names(out)) {
    out[["genes"]] <- lapply(as.character(out[["gene_ids_raw"]]),
                             parse_gene_string)
  }

  if (!"input_direction" %in% names(out)) {
    out[["input_direction"]] <- rep("unspecified", n)
  }

  if (!"ontology" %in% names(out)) {
    out[["ontology"]] <- rep(NA_character_, n)
  }

  out
}


# ---- Named list normalizer ---------------------------------------------------

#' Normalize a named list of enrichment data.frames
#'
#' List names are used as the \code{comparison} field. result_ids are
#' globally unique across all elements.
#'
#' @param enrichment_list A named list of data.frames or enrichResult objects.
#' @param column_map Optional column_map passed through to each normalizer.
#' @return A single combined data.frame.
#' @keywords internal
normalize_list <- function(enrichment_list, column_map = NULL) {
  if (length(enrichment_list) == 0L) {
    return(empty_ora_table())
  }

  if (is.null(names(enrichment_list)) || any(names(enrichment_list) == "")) {
    stop(
      "When providing a list of enrichment results, all elements must be named. ",
      "Names are used as 'comparison' labels."
    )
  }

  parts <- list()
  all_ids <- character(0)

  for (nm in names(enrichment_list)) {
    obj <- enrichment_list[[nm]]

    if (is.null(obj)) next
    if (is.data.frame(obj) && nrow(obj) == 0L) next

    normalized <- normalize_input(obj, column_map = column_map,
                                  comparison = nm)
    normalized[["comparison"]] <- nm

    n <- nrow(normalized)
    new_ids <- make_scoped_result_ids(n, nm, existing_ids = all_ids)
    all_ids <- c(all_ids, new_ids)
    normalized[["result_id"]] <- new_ids

    parts[[nm]] <- normalized
  }

  if (length(parts) == 0L) {
    return(empty_ora_table())
  }

  result <- do.call(rbind, parts)

  # Defensive assertion
  if (anyDuplicated(result[["result_id"]])) {
    stop("Internal error: failed to generate globally unique result_id values.")
  }

  result
}
